### PR TITLE
Add .audioChannel

### PR DESCRIPTION
**Pull request by Oxy949**
The code adds .audioChannel to manually change audio output

Example:
```js
new Sequence()
    .sound("assets/sfx/pistol.mp3")
    .audioChannel("environment")
    .play()
```

### CODE REVIEW

**Comment by Haxxer** [comment]
Nice, thanks for the addition!

I would change it to just `.audioChannel()` to be consistent with the rest of the method wording

**Comment by Oxy949** [comment]
> Nice, thanks for the addition!
> 
> I would change it to just `.audioChannel()` to be consistent with the rest of the method wording

Thanks! Do I need to update the request?

**Comment by Oxy949** [comment]
Done!

**Comment by Haxxer** [comment]
Thanks for the addition!

**Pull request merged**
